### ISSUE TITLE
数据加载下拉列表空白

### ISSUE THREAD

**Issue by Ximeng0918** [kailong321200875/vue2-tree-select#1]
![image](https://user-images.githubusercontent.com/49111698/161375682-771ce753-8d81-4c4f-9bc2-d37c80691218.png)

**Comment by kailong321200875** [comment]
已处理，请申请到最新版本

**Comment by mdxiaohu** [comment]
> 已处理，请申请到最新版本

依旧空白，不知道是不是npm没有更新。

**Comment by kailong321200875** [comment]
@mdxiaohu 线上demo没更新，但是是可以使用的，你可以在自己的开发环境下测试下。
