### ISSUE TITLE
在vue生产环境中 下拉框是空白的 本地正常

### ISSUE THREAD

**Issue by xxcyy** [kailong321200875/vue2-tree-select#2]
![origin_img_v2_bde9e64e-fec4-42e2-8e97-d5399530e30g](https://user-images.githubusercontent.com/20661164/173227193-fc1f37fb-7654-4282-b4fc-9b7cf0ede58c.jpg)
 
![origin_img_v2_12855fac-9e54-43bf-a3ce-460a1df6b51g](https://user-images.githubusercontent.com/20661164/173227208-c598f472-50bf-49f2-8e9d-ae1969201fe0.jpg)

**Comment by kailong321200875** [comment]
这个感觉是你代码的问题。。我这边试了是这场的

**Comment by xxcyy** [comment]
是不是打包环境出了什么问题

**Comment by kailong321200875** [comment]
你用 props 属性去替换别名看看，:props="{label: 'name'}", 然后加上 node-key="id"

**Comment by kailong321200875** [comment]
过滤树形的代码可以不要了

**Comment by xxcyy** [comment]
好的，谢谢
